import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Model = (props) => {
  const { nodes, materials } = useGLTF('./models/camisa_01.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -10, 0]} scale={0.1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['28_Knit_Fleece_Terry_FRONT_109192_0002'].geometry}
          material={materials.Knit_Fleece_Terry_FRONT_109192_16}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['28_Knit_Fleece_Terry_FRONT_109192_0001'].geometry}
          material={materials.Knit_Fleece_Terry_FRONT_109192_15}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['28_Knit_Fleece_Terry_FRONT_109192_0'].geometry}
          material={materials.Knit_Fleece_Terry_FRONT_109192_14}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes['29_Knit_Fleece_Terry_Copy_1_FRONT_109203_0'].geometry
          }
          material={materials.Knit_Fleece_Terry_Copy_1_FRONT_109203_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes['29_Knit_Fleece_Terry_Copy_1_FRONT_109203_0001'].geometry
          }
          material={materials.Knit_Fleece_Terry_Copy_1_FRONT_109203_3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes['29_Knit_Fleece_Terry_Copy_1_FRONT_109203_0002'].geometry
          }
          material={materials.Knit_Fleece_Terry_Copy_1_FRONT_109203_4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['30_Knit_Fleece_Terry_FRONT_109192_0'].geometry}
          material={materials.Knit_Fleece_Terry_FRONT_109192_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['30_Knit_Fleece_Terry_FRONT_109192_0001'].geometry}
          material={materials.Knit_Fleece_Terry_FRONT_109192_3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['30_Knit_Fleece_Terry_FRONT_109192_0002'].geometry}
          material={materials.Knit_Fleece_Terry_FRONT_109192_4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['31_Knit_Fleece_Terry_FRONT_109192_0'].geometry}
          material={materials.Knit_Fleece_Terry_FRONT_109192_5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['31_Knit_Fleece_Terry_FRONT_109192_0002'].geometry}
          material={materials.Knit_Fleece_Terry_FRONT_109192_7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['31_Knit_Fleece_Terry_FRONT_109192_0001'].geometry}
          material={materials.Knit_Fleece_Terry_FRONT_109192_6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['64_Knit_Fleece_Terry_FRONT_109192_0'].geometry}
          material={materials.Knit_Fleece_Terry_FRONT_109192_8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['64_Knit_Fleece_Terry_FRONT_109192_0001'].geometry}
          material={materials.Knit_Fleece_Terry_FRONT_109192_9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['64_Knit_Fleece_Terry_FRONT_109192_0002'].geometry}
          material={materials.Knit_Fleece_Terry_FRONT_109192_10}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['70_Knit_Fleece_Terry_FRONT_109192_0002'].geometry}
          material={materials.Knit_Fleece_Terry_FRONT_109192_13}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['70_Knit_Fleece_Terry_FRONT_109192_0'].geometry}
          material={materials.Knit_Fleece_Terry_FRONT_109192_11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['70_Knit_Fleece_Terry_FRONT_109192_0001'].geometry}
          material={materials.Knit_Fleece_Terry_FRONT_109192_12}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes['71_Knit_Fleece_Terry_Copy_1_FRONT_109203_0'].geometry
          }
          material={materials.Knit_Fleece_Terry_Copy_1_FRONT_109203}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes['71_Knit_Fleece_Terry_Copy_1_FRONT_109203_0001'].geometry
          }
          material={materials.Knit_Fleece_Terry_Copy_1_FRONT_109203_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes['71_Knit_Fleece_Terry_Copy_1_FRONT_109203_0002'].geometry
          }
          material={materials.Knit_Fleece_Terry_Copy_1_FRONT_109203_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.Pattern2D_2949190_Knit_Fleece_Terry_FRONT_109192_0.geometry
          }
          material={materials.Knit_Fleece_Terry_FRONT_109192}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.Pattern2D_2949190_Knit_Fleece_Terry_FRONT_109192_0002.geometry
          }
          material={materials.Knit_Fleece_Terry_FRONT_109192_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.Pattern2D_2949190_Knit_Fleece_Terry_FRONT_109192_0001.geometry
          }
          material={materials.Knit_Fleece_Terry_FRONT_109192_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.Pattern2D_4474558_Knit_Fleece_Terry_Copy_1_FRONT_109203_0001
              .geometry
          }
          material={materials.Knit_Fleece_Terry_Copy_1_FRONT_109203_6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.Pattern2D_4474558_Knit_Fleece_Terry_Copy_1_FRONT_109203_0
              .geometry
          }
          material={materials.Knit_Fleece_Terry_Copy_1_FRONT_109203_5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.Pattern2D_4474558_Knit_Fleece_Terry_Copy_1_FRONT_109203_0002
              .geometry
          }
          material={materials.Knit_Fleece_Terry_Copy_1_FRONT_109203_7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.Pattern2D_4491756_Knit_Fleece_Terry_Copy_1_FRONT_109203_0
              .geometry
          }
          material={materials.Knit_Fleece_Terry_Copy_1_FRONT_109203_8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.Pattern2D_4491756_Knit_Fleece_Terry_Copy_1_FRONT_109203_0002
              .geometry
          }
          material={materials.Knit_Fleece_Terry_Copy_1_FRONT_109203_10}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.Pattern2D_4491756_Knit_Fleece_Terry_Copy_1_FRONT_109203_0001
              .geometry
          }
          material={materials.Knit_Fleece_Terry_Copy_1_FRONT_109203_9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.StitchMatShape_127574_Material109415_0001.geometry}
          material={materials.Material109415}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.StitchMatShape_127574_Material109415_0.geometry}
          material={materials.Material109415}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.StitchMatShape_128590_Material109415_0001.geometry}
          material={materials.Material109415_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.StitchMatShape_128590_Material109415_0.geometry}
          material={materials.Material109415_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.StitchMatShape_129132_Material109415_0.geometry}
          material={materials.Material109415_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.StitchMatShape_130377_Material109415_0.geometry}
          material={materials.Material109415_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.StitchMatShape_130377_Material109415_0001.geometry}
          material={materials.Material109415_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.StitchMatShape_130648_Material109415_0.geometry}
          material={materials.Material109415_3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.StitchMatShape_130909_Material109415_0.geometry}
          material={materials.Material109415_4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.StitchMatShape_132157_Material109415_0001.geometry}
          material={materials.Material109415_5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.StitchMatShape_132157_Material109415_0.geometry}
          material={materials.Material109415_5}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/camisa_01.gltf')
export default Model
